name: ~
description: ~
aggregation:
  metrics:
    - duration
    - power
    - carbon_operational
    - carbon_embodied
    - carbon
  type: both
pipeline:
  compute:
    - cpu-share
    - mem-share
    - weight-cpu-share
    - weight-mem-share
    - reservation-share
    - scale-host-power
    - duration-to-hours
    - calculate-energy
    - sci-o
    - sci-m
    - sum-carbon
initialize:
  plugins:

    cpu-share:
      path: builtin
      method: Divide
      config:
        numerator: cpu_allocated
        denominator: cpu_total
        output: cpu_share

    mem-share:
      path: builtin
      method: Divide
      config:
        numerator: mem_allocated
        denominator: mem_total
        output: mem_share

    weight-cpu-share:
      path: builtin
      method: Coefficient
      config:
        input-parameter: cpu_share
        coefficient: 0.7
        output-parameter: weighted_cpu_share

    weight-mem-share:
      path: builtin
      method: Coefficient
      config:
        input-parameter: mem_share
        coefficient: 0.3
        output-parameter: weighted_mem_share

    reservation-share:
      path: builtin
      method: Sum
      config:
        input-parameters:
          - weighted_cpu_share
          - weighted_mem_share
        output-parameter: reservation_share

    scale-host-power:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - host_power_watts
          - reservation_share
        output-parameter: node_power_watts

    duration-to-hours:
      path: builtin
      method: Coefficient
      config:
        input-parameter: duration
        coefficient: "=1/3600"
        output-parameter: duration_hours

    calculate-energy:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - duration_hours
          - kilowatts
        output-parameter: power
      parameter-metadata:
        outputs:
          power:
            description: Energy consumed per observation interval
            unit: kWh
            aggregation-method:
              time: avg
              component: sum

    sci-o:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - grid_carbon_intensity
          - power
        output-parameter: carbon_operational
      parameter-metadata:
        outputs:
          carbon_operational:
            description: Operational carbon emissions
            unit: gCO2eq
            aggregation-method:
              time: sum
              component: sum

    sci-m:
      path: builtin
      method: SciEmbodied
      config:
        lifespan: 157680000
        output-parameter: carbon_embodied
      mapping:
        vCPUs: cpu_allocated
        memory: mem_allocated
      parameter-metadata:
        outputs:
          carbon_embodied:
            description: Embodied carbon emissions
            unit: gCO2eq
            aggregation-method:
              time: sum
              component: sum

    sum-carbon:
      path: builtin
      method: Sum
      config:
        input-parameters:
          - carbon_operational
          - carbon_embodied
        output-parameter: carbon
      parameter-metadata:
        outputs:
          carbon:
            description: Total carbon emissions
            unit: gCO2eq
            aggregation-method:
              time: sum
              component: sum

tree:
  children:
    ~: ~
